### ISSUE TITLE
Update requirement

### ISSUE THREAD

**Issue by meranote** [up1/soa_group7#13]
Any
- [x] ย้าย access_token ไปไว้ใน Header "Authorization: Bearer <access_token>" ทุกอันที่ต้อง Authenticate

User Service (แยกจาก Authentication)
- [x] ย้าย Register ไปไว้ใน User แทน
- [x] สามารถขอดู User profile โดยไม่ต้อง Authenticate

Post
- [x] สามารถขอดู Post โดยไม่ต้อง Authenticate

Notification
- [ ] นอติแยกตามของแต่ละ Service เช่น `POST /notifications/comment`
- [ ] นอติลืมเก็บเวลา

Comment & Reaction
- [x] Get commentt/reaction no need to authenticate

Service design blueprint
- [x] แก้ให้ตรงกับ API ที่ออกแบบ
- [x] แยก flow การใช้งานของยูสเซอร์/ระบบ
- [x] เพิ่มฐานข้อมูลของ Notification

---

Service Architechure Diagram
- [x] เพิ่ม User Service (แยกออกจาก Authenticate)

**Comment by PhompAng** [comment]
- [x] Search ตอนยังไม่ได้ login 
- [x] add updated_at field

**Comment by PhompAng** [comment]
@chaniwat ฝาก update wiki ล่วยยยย

**Comment by meranote** [comment]
@PhompAng อัพถึงล่าสุดแล้วนะ
@ntsd ฝากแก้ blueprint ด้วยนะ (เพิ่ม notification db อะ)

**Comment by ntsd** [comment]
Guys can you check this https://drive.google.com/drive/u/1/folders/0Bzzio5DpmHhbN29BZWk2U0ZjMTA

@chaniwat  @PhompAng  @EndIess

**Comment by meranote** [comment]
Move to https://github.com/up1/soa_group7/issues/50
