### ISSUE TITLE
embed user role into JWT

### ISSUE THREAD

**Issue by PhompAng** [up1/soa_group7#20]
Should we embed user's role into JWT?
JwtAuthenticationProvider can use comma separated string into authorities list so we can grant some permissions to ADMIN (e.g. remove any post).

**Comment by meranote** [comment]
@PhompAng ok

**Comment by meranote** [comment]
Updated https://github.com/up1/soa_group7/commit/7e5879316ed0b1371386b25f74db315a11dded4d
