### ISSUE TITLE
notification service

### ISSUE THREAD

**Issue by ntsd** [up1/soa_group7#26]

**Comment by ntsd** [comment]
update 

get 1 notification by id 
`GET:http://127.0.0.1:9003/notifications/1`
param

get notification by User with JWT
`GET:http://127.0.0.1:9003/notifications`
body json

create notifications 
`POST:http://127.0.0.1:9003/notifications/create`
body json

update notification'
`PUT:http://127.0.0.1:9003/notifications/update`
body json

**Comment by meranote** [comment]
แก้หน่อยอะ ตอนสร้างทำแยกประเภทไปเลย `POST /notifications/comment`, `POST /notifications/reaction`, `POST /notifications/follow`

update notification ไม่ต้อง /update แล้ว ก็เป็น `PUT /notifications/{id}` เฉยๆ (ส่งไอดีมาด้วย ไม่รู้ว่าจะอัพหาใคร)

**Comment by ntsd** [comment]
อัพว่า read ยัง

**Comment by ntsd** [comment]
เคครับ

**Comment by ntsd** [comment]
คือตอนเขียนเขียนเป็น array อ่ะ ดิ

**Comment by ntsd** [comment]
เพราะ noti ปรกติ มันจะมาพร้อมกันป่ะ เช่น มีคนกด like นี้เเจ้งใครบ้าง

**Comment by ntsd** [comment]
update

get 1 notification by id
GET:http://127.0.0.1:9003/notifications/1

update 1 notification by id
PUT:http://127.0.0.1:9003/notifications/1

get notification by User with JWT
GET:http://127.0.0.1:9003/notifications

create notifications
POST:http://127.0.0.1:9003/notifications

update notifications
PUT:http://127.0.0.1:9003/notifications

create  comment notifications
POST:http://127.0.0.1:9003/notifications/comment

create  reaction notifications
POST:http://127.0.0.1:9003/notifications/reaction

create  follow notifications
POST:http://127.0.0.1:9003/notifications/follow
