### ISSUE TITLE
API Gateway

### ISSUE THREAD

**Issue by meranote** [up1/soa_group7#27]
ศูนย์กลางจักรวาลสำหรับเรียกใช้งานแอปพลิเคชั่น ;w;

- [x] Need to specify server port to each services
- [x] Authorization & Authentication
- [x] Route & Call & Response to other services by `RestTemplate`

---

Services
- [x] Authentication
- [x] User
- [x] Follow
- [x] Post
- [x] Comment
- [x] Reaction
- [x] Notification

---

[33. Calling REST services](http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-restclient.html)
[Calling REST service with Spring RestTemplate](https://www.leveluplunch.com/java/tutorials/015-consuming-rest-webservice-with-spring-resttemplate/)

**Comment by PhompAng** [comment]
Auth service => 9005
User service => 9001
Post service => 9002

**Comment by ntsd** [comment]
Notification => 9003

**Comment by meranote** [comment]
สำหรับ service ที่ยังไม่ได้กำหนด port เด๋วเรากำหนดเอาเลยนะ
(เด๋วบันทึกลง wiki)
