### ISSUE TITLE
Embed user's post count in user table

### ISSUE THREAD

**Issue by PhompAng** [up1/soa_group7#32]

**Comment by meranote** [comment]
@EndIess เพิ่ม user db นับ post count อะะ + ทำ resource api เพื่อเรียก เพิ่ม/ลด (ดูแบบใน post-service) อะ

**Comment by PhompAng** [comment]
Update user model in other services

**Comment by meranote** [comment]
ทำ resource ให้แล้วนะ ฝากเขียน method repository สำหรับเพิ่ม/ลดด้วยนะ

**Comment by meranote** [comment]
Done (and with user update `PUT users/self`) https://github.com/up1/soa_group7/commit/83576ededd4ad03956abb8bc50fd926e681738a0
