### ISSUE TITLE
Deploy services for frontend devlopment & testing

### ISSUE THREAD

**Issue by meranote** [up1/soa_group7#38]
Public IP for calling api : 35.185.168.160:80 (via api-gateway)

- ~~setup additional domain (api.shenzhentagram.cc or api.shenzhentagram.meranote.in.th ;w;) in GCP~~ <br>will do in future (https://github.com/up1/soa_group7/issues/44)
- ~~automatic rolling update for container (tag:latest, easily and good for lazy ;w;)~~

@PhompAng Some api-resource may not working yet (Take a long time to implement api-gateway to call non-Spring boot project, testing). Authenticate, User, Post services are ready, Will implement anothers ASAP.

@ntsd @EndIess For authenticate, user, post service, If want to fix the service just do in develop branch, push it and calling me so i can update an image (and version-tag) and roll the update. For other service just do as normal (but if you finished it just merge into develop and call me so i will implement the APIs, setup a dockerfile and deploy the service)

Will setup an orgainzation docker repo so you guys can push an image and roll the update. XD (if possible)

---

Deployed status
- API-Gateway: meranote/api-gateway:0.1.5
- Authentication : meranote/authentication-service:0.1
- User: meranote/user-service:0.2.4
- Post: meranote/post-service:0.1.1

**Comment by PhompAng** [comment]
Post service is not ready. Missing ```/posts/{id}/comments/count```, ```/posts/{id}/reactions/count```, and ```/users/{user_id}/posts```.

**Comment by meranote** [comment]
Update at https://github.com/up1/soa_group7/commit/7ebde4e8bf50dbff8d24d661fe52fc3f550a59cc

Note: `/posts/{id}/comments/count` and `/posts/{id}/reactions/count` only call from internal api

**Comment by meranote** [comment]
Done https://github.com/up1/soa_group7/commit/4e2f4c067a7c953640346699a8bb8e961ad3b97e
