### ISSUE TITLE
embed user in post response

### ISSUE THREAD

**Issue by PhompAng** [up1/soa_group7#42]

**Comment by meranote** [comment]
API Gateway: Get user From User Service, to embeded user detail into any post response

**Comment by PhompAng** [comment]
DO THIS

**Comment by meranote** [comment]
Updated https://github.com/up1/soa_group7/commit/58284617fafe2c2a3444bd3dfaa91aa4940296c0

![image](https://cloud.githubusercontent.com/assets/3206134/25002790/695a2308-2076-11e7-8e57-24aa692ba45d.png)
