### ISSUE TITLE
Follow Service

### ISSUE THREAD

**Issue by meranote** [up1/soa_group7#49]

**Comment by meranote** [comment]
เช็คแล้วนะ

แก้ให้ output ออกตามนี้
![image](https://cloud.githubusercontent.com/assets/3206134/25326331/ece03312-28f9-11e7-9db4-9dce6380f0de.png)

- ในฐานข้อมูลอะเก็บทั้ง 2 อันเลย ทั้ง follower กับ following ต่อ 1 user (เท่ากับว่าถ้า follow ต้องอัพเดท following ที่ตัวเอง และอัพเดท follower ที่เป้าหมายที่เราจะ follow ไป)
- ลบ POST /users/{id}/followed_by ออก (ใช้แค่ POST /users/{id}/follows)
- POST /users/{id}/follows : {id} คือเป้าหมายที่จะ follow ส่วนใน payload (userId) คือ user ที่ follow {id} นั้น (หรือก็คือ user ที่ login/authen อยู่)
- DELETE /users/{id}/followed_by ใช้แค่ DELETE /users/{id}/follows และก็เหมือนข้างบน, {id} คือเป้าหมายที่ unfollow

เช็คตามข้างบนนะ เราเข้าใจว่าเป็นแบบนี้ *3* (เด๋วจะเขียน api gateway และก็ setup mongo ข้างบนรอ)

**Comment by chaniwat** [comment]
เพิ่งเช็ค document เอาตามข้างบนนี้เลยนะ
