### ISSUE TITLE
Need to review and redesign documents

### ISSUE THREAD

**Issue by meranote** [up1/soa_group7#50]
จาก https://github.com/up1/soa_group7/issues/13 และ https://github.com/up1/soa_group7/issues/46

อยากให้ช่วยดู feature/flow อีกที แล้วก็ปรับ flow หรือ แยก flow เพิ่มเติม ถ้าจำเป็น (จาก Present#4) ก่อนจะจบ Sprint#3 (หรือ Present#5) เพื่อจะได้แบ่งงานได้สะดวกขึ้น - แตกเป็น issue แยกไปได้เลยนะ จะได้ติดตามง่าย

อยากให้ปรับเป็น 1 flow ต่อ 1 ฟังก์ชั่น/ฟีเจอร์ ตามการใช้งานจริงๆ (ให้คิดตาม UI อะ เช่น โพสต์งี้ ก่อนโพสต์ล๊อกอิน หลังโพสต์ดูโพสต์ที่เพิ่งอัพ) จะได้ง่ายตอนไปทำ Web/UI และก็ **แบ่งงาน** .__.

ส่วนที่ค้าง
- [x] นอติแยกตามของแต่ละ Service เช่น POST /notifications/comment
- [x] นอติลืมเก็บเวลา

[APIs Sheet (Resources)](https://docs.google.com/spreadsheets/d/1uVrQ9Htw3ilPNmY5TEB8type_NYLG6kBHFvD0oOf_II)

**Comment by ntsd** [comment]
เเยกเเล้ว
ใส่ time เเล้วนะ
