### ISSUE TITLE
Setup & Deploy monitoring with Prometheus and Grafana 

### ISSUE THREAD

**Issue by meranote** [up1/soa_group7#56]
[Prometheus: Using docker (Custom image)](https://prometheus.io/docs/introduction/install/#using-docker)
[Grafana-docker](https://github.com/grafana/grafana-docker)

- [ ] Monitoring services
- [x] Monitoring gateway
- [ ] Monitoring kubernetes (google cloud)

---

Custom metric in api-gateway
[Monitoring Spring Boot Applications with Prometheus](https://raymondhlee.wordpress.com/2016/09/24/monitoring-spring-boot-applications-with-prometheus/) [(Part 2)](https://raymondhlee.wordpress.com/2016/10/03/monitoring-spring-boot-applications-with-prometheus-part-2/)

**Comment by meranote** [comment]
@EndIess นัททำลง Servicce อันไหนแล้วติ๊กให้ทีนะ (ถ้าอันไหนไม่ใช่ spring boot ให้ mention หาเจ้าของให้เขาทำนะ -3-)

- [ ] Authentication
- [ ] User
- [ ] Post
- [ ] Follow
- [ ] Notification
- [ ] Comment
- [ ] Reaction

**Comment by ntsd** [comment]
เดี๋ยวกูทำ service  ที่เป็น node

**Comment by ntsd** [comment]
ตอนนี้ขอเปลี่ยนใหม่ คือทำใน Gateway ของเเต่ละ Service ครบเรียบร้อย
