### ISSUE TITLE
Don't know the total items of notification

### ISSUE THREAD

**Issue by meranote** [up1/soa_group7#57]
@ntsd Can you implement the total count of notification items, total page or etcs. (Like Pageable in post-service) It's will help frontend to detemined should fetching the next notifications set or not

Implement only at com.shenzhentagram.NotificationController.getNotificationsByUser() (or plus others at your opinion XD)

**Comment by ntsd** [comment]
เลือกดึงเฉพาะที่ยังไม่ checked ดีกว่านะ

**Comment by ntsd** [comment]
ทำเเบบโหลดมาเรื่อยๆได้ไหมอ่ะ  

ถ้าดึงมา เเล้วได้ 0 ค่อยดัก ไม่งั้น count รอบ เเล้วget อีกรอบไม่ช้าเหรอ

Example https://www.facebook.com/notifications

เดี๋ยวทำ เเบบเรียงตามเวลาให้
