### ISSUE TITLE
Subtype notification problem

### ISSUE THREAD

**Issue by meranote** [up1/soa_group7#69]
![image](https://cloud.githubusercontent.com/assets/3206134/25456372/f0faae1e-2afc-11e7-9f45-49b3e643f971.png)

From is null when serialize to json string (in api-gateway: noitification controller, notification models)

**Comment by meranote** [comment]
![image](https://cloud.githubusercontent.com/assets/3206134/25456481/2ff1a136-2afd-11e7-9356-6e1c8b867beb.png)

**Comment by ntsd** [comment]
you need to set type

**Comment by ntsd** [comment]
you can check it with Postman 

https://github.com/up1/soa_group7/blob/develop/Shenzhentagram.postman_collection.json
